openapi: 3.2.0
info:
  title: OpenCV Face Recognition Face Verification API
  description: OpenCV Face Recognition allows you to either **manually** (through our Developer Portal UI) or **programmatically** (through our SDKs or REST API) detect, recognize, and verify faces in images.
  version: 2026.07.15.0759
tags:
- name: Face Verification
  description: The `/compare` endpoint allows you to compare two sets of face images to determine if they correspond to the same person.
paths:
  /compare:
    post:
      tags:
      - Face Verification
      summary: Compare Two Lists Of Images Of Same Person
      operationId: compare_two_lists_of_images_of_same_person_compare_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompareSchema'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreSchema'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - APIKeyHeader: []
  /compare-live-face:
    post:
      tags:
      - Face Verification
      summary: Compare Live Face To Gallery Images Of Same Person
      operationId: compare_live_face_to_gallery_images_of_same_person_compare_live_face_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompareLiveFaceSchema'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreLiveFaceSchema'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - APIKeyHeader: []
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    CompareLiveFaceSchema:
      properties:
        probe:
          type: string
          title: Probe
        gallery:
          items:
            type: string
          type: array
          maxItems: 3
          minItems: 1
          title: Gallery
        os:
          anyOf:
          - $ref: '#/components/schemas/OSEnum'
          - type: 'null'
          default: DESKTOP
        search_mode:
          anyOf:
          - $ref: '#/components/schemas/SearchModeEnum'
          - type: 'null'
          default: FAST
        liveness_min_score:
          anyOf:
          - type: number
            maximum: 1.0
            minimum: 0.0
          - type: string
          - type: 'null'
          title: Liveness Min Score
          default: 0.5
      type: object
      required:
      - probe
      - gallery
      title: CompareLiveFaceSchema
      example:
        gallery:
        - base64_encoded_string
        liveness_min_score: 0.5
        os: DESKTOP
        probe: base64_encoded_string
        search_mode: FAST/ACCURATE choose one, default FAST
    ScoreSchema:
      properties:
        score:
          type: number
          title: Score
      type: object
      required:
      - score
      title: ScoreSchema
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OSEnum:
      type: string
      enum:
      - DESKTOP
      - ANDROID
      - IOS
      title: OSEnum
    SearchModeEnum:
      type: string
      enum:
      - ACCURATE
      - FAST
      title: SearchModeEnum
    ScoreLiveFaceSchema:
      properties:
        score:
          type: number
          title: Score
        liveness_score:
          type: string
          title: Liveness Score
      type: object
      required:
      - score
      - liveness_score
      title: ScoreLiveFaceSchema
    CompareSchema:
      properties:
        probe:
          items:
            type: string
          type: array
          maxItems: 3
          minItems: 1
          title: Probe
        gallery:
          items:
            type: string
          type: array
          maxItems: 3
          minItems: 1
          title: Gallery
        search_mode:
          anyOf:
          - $ref: '#/components/schemas/SearchModeEnum'
          - type: 'null'
          default: FAST
      type: object
      required:
      - probe
      - gallery
      title: CompareSchema
      example:
        gallery:
        - base64_encoded_string
        probe:
        - base64_encoded_string
        search_mode: FAST/ACCURATE choose one, default FAST
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: x-api-key
