openapi: 3.2.0
info:
  title: OpenCV Face Recognition Face Anti-Spoofing / Liveness API
  description: OpenCV Face Recognition allows you to either **manually** (through our Developer Portal UI) or **programmatically** (through our SDKs or REST API) detect, recognize, and verify faces in images.
  version: 2026.07.15.0759
tags:
- name: Face Anti-Spoofing / Liveness
  description: The `/liveness` endpoint allows you to determine if a face image is of a real person or a spoofed image (eg.
paths:
  /liveness:
    post:
      tags:
      - Face Anti-Spoofing / Liveness
      summary: Check Liveness For A Single Image
      operationId: check_liveness_for_a_single_image_liveness_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LivenessSchema'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessResultSchema'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - APIKeyHeader: []
components:
  schemas:
    LivenessResultSchema:
      properties:
        liveness_score:
          type: number
          title: Liveness Score
      type: object
      required:
      - liveness_score
      title: LivenessResultSchema
    LivenessSchema:
      properties:
        os:
          anyOf:
          - $ref: '#/components/schemas/OSEnum'
          - type: 'null'
          default: DESKTOP
        image:
          type: string
          title: Image
      type: object
      required:
      - image
      title: LivenessSchema
      example:
        image: base64_encoded_string
        os: DESKTOP
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OSEnum:
      type: string
      enum:
      - DESKTOP
      - ANDROID
      - IOS
      title: OSEnum
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: x-api-key
